Repository NNPDF/nnpdf, pull requests merged in 2021-12, with the labels that each got.

#1477 Dispatching Python covariance matrices
  validphys2/src/validphys/config.py
  validphys2/src/validphys/covmats.py
  validphys2/src/validphys/tests/regressions/test_regularized_covmat_generation.csv
  validphys2/src/validphys/tests/regressions/test_t0covmat.csv
  validphys2/src/validphys/tests/regressions/test_t0sqrtcovmat.csv
  validphys2/src/validphys/tests/test_covmatreg.py
  validphys2/src/validphys/tests/test_regressions.py
Labels: destroyingc++

#1472 In process_function take nnpdf31_process from PLOTTING_*.yaml
  validphys2/src/validphys/config.py
  validphys2/src/validphys/theorycovariance/theorycovarianceutils.py
Labels: bug

#1192 CMS high-mass Drell-Yan at 13 TeV
  buildmaster/filters/CMS_HMDY_13TEV.cc
  buildmaster/inc/CMS_HMDY_13TEV.h
  buildmaster/meta/CMS_HMDY_13TEV.yaml
  buildmaster/meta/CMS_HMDY_DE_13TEV.yaml
  buildmaster/meta/CMS_HMDY_DM_13TEV.yaml
  buildmaster/rawdata/CMS_HMDY_13TEV/CMS_HMDY_13TEV.cov
  buildmaster/rawdata/CMS_HMDY_13TEV/CMS_HMDY_13TEV.data
  buildmaster/rawdata/CMS_HMDY_DE_13TEV/CMS_HMDY_DE_13TEV.cov
  buildmaster/rawdata/CMS_HMDY_DE_13TEV/CMS_HMDY_DE_13TEV.data
  buildmaster/rawdata/CMS_HMDY_DM_13TEV/CMS_HMDY_DM_13TEV.cov
  buildmaster/rawdata/CMS_HMDY_DM_13TEV/CMS_HMDY_DM_13TEV.data
  buildmaster/src/buildmaster.cc
  nnpdfcpp/data/commondata/DATA_CMS_HMDY_13TEV.dat
  nnpdfcpp/data/commondata/DATA_CMS_HMDY_DE_13TEV.dat
  nnpdfcpp/data/commondata/DATA_CMS_HMDY_DM_13TEV.dat
  nnpdfcpp/data/commondata/PLOTTING_CMS_HMDY_13TEV.yaml
  nnpdfcpp/data/commondata/PLOTTING_CMS_HMDY_DE_13TEV.yaml
  nnpdfcpp/data/commondata/PLOTTING_CMS_HMDY_DM_13TEV.yaml
  nnpdfcpp/data/commondata/systypes/SYSTYPE_CMS_HMDY_13TEV_DEFAULT.dat
  nnpdfcpp/data/commondata/systypes/SYSTYPE_CMS_HMDY_DE_13TEV_DEFAULT.dat
  nnpdfcpp/data/commondata/systypes/SYSTYPE_CMS_HMDY_DM_13TEV_DEFAULT.dat
Labels: buildmaster, NNPDF4.1

#1430 Change ThPredictions to python predictions
  validphys2/examples/cuts_options.yaml
  validphys2/examples/data_theory_comparison.yaml
  validphys2/examples/export_data.yaml
  validphys2/examples/looping_example.yaml
  validphys2/examples/plot_phi.yaml
  validphys2/src/validphys/closuretest/multiclosure.py
  validphys2/src/validphys/core.py
  validphys2/src/validphys/covmats.py
  validphys2/src/validphys/results.py
  validphys2/src/validphys/tests/baseline/test_dataspecschi2.png
  validphys2/src/validphys/tests/regressions/test_datasetchi2.csv
  validphys2/src/validphys/tests/regressions/test_pdf_plus_exp_covmat.csv
  validphys2/src/validphys/tests/regressions/test_replicachi2data.csv
  validphys2/src/validphys/tests/regressions/test_thprediction_results_hessian.csv
Labels: enhancement, Core changes, destroyingc++, run-fit-bot

#1485 Improve postfit error message
  validphys2/src/validphys/scripts/postfit.py
Labels: enhancement
