Repository NNPDF/nnpdf, pull requests merged in 2021-11, with the labels that each got.

#1454 mention rolling release in README
  README.md
Labels: documentation

#1456 rename meta/integ files
  buildmaster/meta/INTEGXV.yaml
  buildmaster/meta/INTEGXV3.yaml
  buildmaster/meta/INTEGXV8.yaml
Labels: bug

#1461 Changed reserve -> resize in FutureColliders.cc in buildmaster
  buildmaster/filters/FutureColliders.cc
Labels: bug

#1463 Enable python 3.9 and mamba build
  .github/workflows/docker.yml
  .github/workflows/fitbot.yml
  .github/workflows/tests.yml
  conda-recipe/meta.yaml
  libnnpdf/wrapper/CMakeLists.txt
Labels: run-fit-bot, devtools

#1465 Fix undefined behaviour in buildmater number parsing
  buildmaster/rawdata/NMCPD/proton_ite/output/tables/group_result_table.csv
Labels: bug

#1467 Disable spinner in non interactive mode
  validphys2/src/validphys/renametools.py
Labels: enhancement

#1466 Fix pseudodata indexing mismatch
  validphys2/src/validphys/commondata.py
  validphys2/src/validphys/pseudodata.py
Labels: bug, urgent, run-fit-bot

#1424 Changing functions which are still using NNPDF pseudodata
  validphys2/examples/mc_gen_example.yaml
  validphys2/src/validphys/chi2grids.py
  validphys2/src/validphys/config.py
  validphys2/src/validphys/filters.py
  validphys2/src/validphys/mc_gen.py
  validphys2/src/validphys/n3fit_data.py
  validphys2/src/validphys/n3fit_data_utils.py
  validphys2/src/validphys/pseudodata.py
  validphys2/src/validphys/results.py
  validphys2/src/validphys/tests/regressions/test_art_rep_generation.csv
  validphys2/src/validphys/tests/test_regressions.py
Labels: destroyingc++
