Repository NNPDF/nnpdf, pull requests merged in 2022-02, with the labels that each got.

#1506 Add a fallback to using all points for reports that are using old fits with bad filters.
  validphys2/src/validphys/config.py
  validphys2/src/validphys/core.py
  validphys2/src/validphys/loader.py
  validphys2/src/validphys/tests/test_commondataparser.py
  validphys2/src/validphys/tests/test_loader.py
Labels: legacy

#1501 Swap libNNPDF LHAPDFSet for a python PDF object
  doc/sphinx/source/vp/examples.rst
  doc/sphinx/source/vp/pydataobjs.rst
  validphys2/src/validphys/app.py
  validphys2/src/validphys/checks.py
  validphys2/src/validphys/config.py
  validphys2/src/validphys/core.py
  validphys2/src/validphys/filters.py
  validphys2/src/validphys/gridvalues.py
  validphys2/src/validphys/lhapdfset.py
  validphys2/src/validphys/results.py
  validphys2/src/validphys/sumrules.py
  validphys2/src/validphys/tests/conftest.py
Labels: destroyingc++, run-fit-bot

#1510 Use python convolutions also for positivity predictions
  validphys2/src/validphys/convolution.py
  validphys2/src/validphys/core.py
  validphys2/src/validphys/dataplots.py
  validphys2/src/validphys/results.py
  validphys2/src/validphys/tests/conftest.py
  validphys2/src/validphys/tests/test_commondataparser.py
  validphys2/src/validphys/tests/test_pyfkdata.py
Labels: destroyingc++

#1514 Make saved pseudodata match fitted pseudodata
  n3fit/src/n3fit/tests/regressions/quickcard_1.json
  n3fit/src/n3fit/tests/regressions/quickcard_2.json
  validphys2/src/validphys/n3fit_data.py
  validphys2/src/validphys/pseudodata.py
  validphys2/src/validphys/tests/conftest.py
  validphys2/src/validphys/tests/regressions/test_art_rep_generation.csv
  validphys2/src/validphys/tests/regressions/test_mcreplica.csv
  validphys2/src/validphys/tests/test_pseudodata.py
Labels: run-fit-bot

#1518 Documentation madgraph+amcfast
  doc/sphinx/source/tutorials/APPLgrids.md
Labels: documentation

#1525 Fix callers of group_chi2_table
  validphys2/src/validphys/results.py
  validphys2/src/validphys/theorycovariance/output.py
Labels: bug
