Repository NNPDF/nnpdf, pull requests merged in 2022-03, with the labels that each got.

#1533 Bugfix hyperopt integrability penalty
  n3fit/src/n3fit/hyper_optimization/penalties.py
  n3fit/src/n3fit/tests/regressions/hyper-quickcard.yml
Labels: bug

#1515 Utilize stats everywhere where it can be used
  n3fit/src/n3fit/tests/test_vpinterface.py
  n3fit/src/n3fit/vpinterface.py
  validphys2/src/validphys/arclength.py
  validphys2/src/validphys/calcutils.py
  validphys2/src/validphys/closuretest/closure_results.py
  validphys2/src/validphys/closuretest/multiclosure.py
  validphys2/src/validphys/closuretest/multiclosure_pdf.py
  validphys2/src/validphys/closuretest/multiclosure_pseudodata.py
  validphys2/src/validphys/correlations.py
  validphys2/src/validphys/covmats.py
  validphys2/src/validphys/dataplots.py
  validphys2/src/validphys/deltachi2.py
  validphys2/src/validphys/eff_exponents.py
  validphys2/src/validphys/mc2hessian.py
  validphys2/src/validphys/pdfgrids.py
  validphys2/src/validphys/pdfplots.py
  validphys2/src/validphys/replica_selector.py
  validphys2/src/validphys/results.py
  validphys2/src/validphys/tests/baseline/test_dataspecschi2.png
  validphys2/src/validphys/tests/regressions/test_datasetchi2.csv
  validphys2/src/validphys/tests/regressions/test_replicachi2data.csv
  validphys2/src/validphys/tests/test_closuretest.py
  validphys2/src/validphys/tests/test_pyfkdata.py
Labels: destroyingc++

#1517 use error_members instead of rawdata
  n3fit/src/n3fit/tests/test_vpinterface.py
  validphys2/src/validphys/arclength.py
  validphys2/src/validphys/calcutils.py
  validphys2/src/validphys/closuretest/closure_results.py
  validphys2/src/validphys/closuretest/multiclosure.py
  validphys2/src/validphys/closuretest/multiclosure_pdf.py
  validphys2/src/validphys/closuretest/multiclosure_pseudodata.py
  validphys2/src/validphys/correlations.py
  validphys2/src/validphys/covmats.py
  validphys2/src/validphys/dataplots.py
  validphys2/src/validphys/deltachi2.py
  validphys2/src/validphys/paramfits/plots.py
  validphys2/src/validphys/pdfgrids.py
  validphys2/src/validphys/pdfplots.py
  validphys2/src/validphys/replica_selector.py
  validphys2/src/validphys/results.py
  validphys2/src/validphys/reweighting.py
  validphys2/src/validphys/tests/test_closuretest.py
  validphys2/src/validphys/tests/test_pyfkdata.py
Labels: destroyingc++

#1534 adjust hyper_scan step sizes
  n3fit/src/n3fit/hyper_optimization/hyper_scan.py
Labels: hyperoptimization

#1522 Return all members when using MC PDFs
  n3fit/src/n3fit/io/writer.py
  n3fit/src/n3fit/performfit.py
  n3fit/src/n3fit/tests/test_vpinterface.py
  n3fit/src/n3fit/vpinterface.py
  validphys2/src/validphys/arclength.py
  validphys2/src/validphys/convolution.py
  validphys2/src/validphys/core.py
  validphys2/src/validphys/correlations.py
  validphys2/src/validphys/dataplots.py
  validphys2/src/validphys/deltachi2.py
  validphys2/src/validphys/gridvalues.py
  validphys2/src/validphys/lhapdfset.py
  validphys2/src/validphys/pdfgrids.py
  validphys2/src/validphys/results.py
  validphys2/src/validphys/sumrules.py
  validphys2/src/validphys/tests/baseline/test_dataspecschi2.png
  validphys2/src/validphys/tests/regressions/test_datasetchi2.csv
  validphys2/src/validphys/tests/regressions/test_replicachi2data.csv
  validphys2/src/validphys/tests/regressions/test_sum_rules_MC.csv
  validphys2/src/validphys/tests/regressions/test_sum_rules_hessian.csv
  validphys2/src/validphys/tests/test_core.py
Labels: destroyingc++
