Repository NNPDF/nnpdf, pull requests merged in 2022-01, with the labels that each got.

#1497 Add documentation on adding citations to Sphinx
  doc/sphinx/source/contributing/index.rst
  doc/sphinx/source/contributing/sphinx-documentation.md
  doc/sphinx/source/contributing/sphinx-documentation.rst
Labels: documentation

#1495 Add an overview of loss functions to the documentation
  doc/sphinx/source/figuresofmerit/index.rst
  doc/sphinx/source/index.rst
  doc/sphinx/source/n3fit/runcard_detailed.rst
  doc/sphinx/source/references.bib
  doc/sphinx/source/tutorials/thcov_tutorial.rst
  validphys2/src/validphys/theorycovariance/theorycovarianceutils.py
Labels: documentation

#1489 Use python covmat in multiclosure tests
  validphys2/src/validphys/checks.py
  validphys2/src/validphys/closuretest/closure_checks.py
  validphys2/src/validphys/closuretest/multiclosure.py
  validphys2/src/validphys/config.py
Labels: destroyingc++

#1483 Handle corrupt figures in report indexing
  validphys2/serverscripts/index-reports.py
Labels: enhancement
