Repository NNPDF/nnpdf, pull requests merged in 2023-03, with the labels that each got.

#1680 Remove libNNPDF from python
  doc/sphinx/source/data/plotting_format.md
  doc/sphinx/source/tutorials/addspecialgrouping.rst
  doc/sphinx/source/vp/custom_pipelines.rst
  doc/sphinx/source/vp/dataspecification.rst
  doc/sphinx/source/vp/datthcomp.md
  doc/sphinx/source/vp/developer.rst
  doc/sphinx/source/vp/index.rst
  doc/sphinx/source/vp/pydataobjs.rst
  validphys2/examples/mc_gen_report.md
  validphys2/src/validphys/app.py
  validphys2/src/validphys/calcutils.py
  validphys2/src/validphys/closuretest/multiclosure_pseudodata.py
  validphys2/src/validphys/commondataparser.py
  validphys2/src/validphys/config.py
  validphys2/src/validphys/core.py
  validphys2/src/validphys/coredata.py
  validphys2/src/validphys/dataplots.py
  validphys2/src/validphys/fkparser.py
  validphys2/src/validphys/kinematics.py
  validphys2/src/validphys/lhapdfset.py
  validphys2/src/validphys/loader.py
  validphys2/src/validphys/mc_gen.py
  validphys2/src/validphys/n3fit_data.py
  validphys2/src/validphys/n3fit_data_utils.py
  validphys2/src/validphys/plotoptions/core.py
  validphys2/src/validphys/results.py
  validphys2/src/validphys/sumrules.py
  validphys2/src/validphys/tests/test_covmats.py
  validphys2/src/validphys/tests/test_weights.py
Labels: destroyingc++

#1694 Evolve n3fit with eko 0.12
  conda-recipe/meta.yaml
  n3fit/src/evolven3fit_new/eko_utils.py
  n3fit/src/evolven3fit_new/evolve.py
  n3fit/src/n3fit/scripts/evolven3fit_new.py
  n3fit/src/n3fit/tests/regressions/quickcard_1.json
  n3fit/src/n3fit/tests/regressions/quickcard_2.json
  n3fit/src/n3fit/tests/test_evolven3fit.py
Labels: enhancement

#1696 read NN output size for hyperscan from runcard
  n3fit/src/n3fit/hyper_optimization/hyper_scan.py
Labels: enhancement, hyperoptimization

#1607 Mix bands and replicas
  validphys2/examples/mixbandreplicas.yaml
  validphys2/src/validphys/checks.py
  validphys2/src/validphys/pdfplots.py
Labels: enhancement
