Repository NNPDF/nnpdf, pull requests merged in 2023-10, with the labels that each got.

#1792 Refactor stopping
  n3fit/src/n3fit/io/writer.py
  n3fit/src/n3fit/performfit.py
  n3fit/src/n3fit/stopping.py
Labels: Refactoring, n3fit, run-fit-bot

#1820 bugfix with stopping
  n3fit/src/n3fit/stopping.py
Labels: bug

#1828 add skip_magic_trailing_comma to black config
  pyproject.toml
Labels: devtools
