Repository NNPDF/nnpdf, pull requests merged in 2023-11, with the labels that each got.

#1850 use mamba in docker construction
  .github/workflows/docker.yml
  docker/dockerfile
Labels: devtools

#1867 Order dataset differences by name of the commondata
  validphys2/src/validphys/fitdata.py
Labels: enhancement, validphys

#1874 add explicit cut for FONLL-E
  nnpdfcpp/data/theory.db
  validphys2/src/validphys/cuts/filters.yaml
Labels: bug
