Repository NNPDF/nnpdf, pull requests merged in 2023-12, with the labels that each got.

#1818 Multi dense logistics
  n3fit/src/n3fit/backends/keras_backend/MetaModel.py
  n3fit/src/n3fit/hyper_optimization/penalties.py
  n3fit/src/n3fit/hyper_optimization/rewards.py
  n3fit/src/n3fit/layers/msr_normalization.py
  n3fit/src/n3fit/layers/rotations.py
  n3fit/src/n3fit/model_gen.py
  n3fit/src/n3fit/model_trainer.py
  n3fit/src/n3fit/msr.py
  n3fit/src/n3fit/performfit.py
  n3fit/src/n3fit/stopping.py
  n3fit/src/n3fit/tests/test_msr.py
  n3fit/src/n3fit/tests/test_multireplica.py
  n3fit/src/n3fit/tests/test_penalties.py
  n3fit/src/n3fit/tests/test_vpinterface.py
  validphys2/src/validphys/photon/compute.py
  validphys2/src/validphys/tests/photon/test_compute.py
Labels: enhancement, Refactoring, urgent, run-fit-bot, escience

#1877 Move replica axis to front everywhere
  n3fit/src/n3fit/backends/keras_backend/MetaModel.py
  n3fit/src/n3fit/backends/keras_backend/operations.py
  n3fit/src/n3fit/hyper_optimization/penalties.py
  n3fit/src/n3fit/layers/DIS.py
  n3fit/src/n3fit/layers/DY.py
  n3fit/src/n3fit/layers/msr_normalization.py
  n3fit/src/n3fit/layers/rotations.py
  n3fit/src/n3fit/layers/x_operations.py
  n3fit/src/n3fit/model_gen.py
  n3fit/src/n3fit/model_trainer.py
  n3fit/src/n3fit/msr.py
  n3fit/src/n3fit/stopping.py
  n3fit/src/n3fit/tests/test_layers.py
  n3fit/src/n3fit/tests/test_msr.py
  n3fit/src/n3fit/tests/test_multireplica.py
  n3fit/src/n3fit/tests/test_rotations.py
  n3fit/src/n3fit/tests/test_xops.py
  validphys2/src/validphys/photon/compute.py
  validphys2/src/validphys/tests/photon/test_compute.py
Labels: Refactoring, n3fit, run-fit-bot, escience

#1897 also upload conda package if push corresponds to a tag creation
  .github/workflows/tests.yml
Labels: devtools

#1898 Fix photon replicas generation + make vp-nextfitruncard use Q0 instead of Qmin for iterating preprocessing
  n3fit/src/n3fit/backends/keras_backend/MetaModel.py
  n3fit/src/n3fit/checks.py
  n3fit/src/n3fit/model_gen.py
  n3fit/src/n3fit/model_trainer.py
  n3fit/src/n3fit/performfit.py
  validphys2/src/validphys/config.py
  validphys2/src/validphys/eff_exponents.py
Labels: bug

#1899 Fix dataset/prediction ordering problem in theory covmat creation
  validphys2/src/validphys/results.py
  validphys2/src/validphys/theorycovariance/construction.py
  validphys2/src/validphys/theorycovariance/tests.py
Labels: bug

#1900 add description of 4.0.7 release to docs
  doc/sphinx/source/releases.rst
Labels: documentation
