Repository NNPDF/nnpdf, pull requests merged in 2024-09, with the labels that each got.

#2148 fix ModSV in polarized theories
  nnpdf_data/nnpdf_data/theory_cards/41100001.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100002.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100003.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100006.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100007.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100008.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100011.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100012.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100013.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100016.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100017.yaml
  nnpdf_data/nnpdf_data/theory_cards/41100018.yaml
Labels: bug, Polarised

#2154 Sihp data
  doc/sphinx/source/data/dataset-naming-convention.rst
  nnpdf_data/nnpdf_data/commondata/PHENIX-2009_SHP_200GEV_PI0/data.yaml
  nnpdf_data/nnpdf_data/commondata/PHENIX-2009_SHP_200GEV_PI0/filter.py
  nnpdf_data/nnpdf_data/commondata/PHENIX-2009_SHP_200GEV_PI0/kinematics.yaml
  nnpdf_data/nnpdf_data/commondata/PHENIX-2009_SHP_200GEV_PI0/metadata.yaml
  nnpdf_data/nnpdf_data/commondata/PHENIX-2009_SHP_200GEV_PI0/rawdata/HEPData-ins1282448-v1-Table_7.yaml
  nnpdf_data/nnpdf_data/commondata/PHENIX-2009_SHP_200GEV_PI0/uncertainties.yaml
  nnpdf_data/nnpdf_data/commondata/PHENIX-2013_SHP_510GEV_PI0/data.yaml
  nnpdf_data/nnpdf_data/commondata/PHENIX-2013_SHP_510GEV_PI0/filter.py
  nnpdf_data/nnpdf_data/commondata/PHENIX-2013_SHP_510GEV_PI0/kinematics.yaml
  nnpdf_data/nnpdf_data/commondata/PHENIX-2013_SHP_510GEV_PI0/metadata.yaml
  nnpdf_data/nnpdf_data/commondata/PHENIX-2013_SHP_510GEV_PI0/rawdata/HEPData-ins1396712-v1-Figure_3.yaml
  nnpdf_data/nnpdf_data/commondata/PHENIX-2013_SHP_510GEV_PI0/uncertainties.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2006_SHP_200GEV_PI0/data.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2006_SHP_200GEV_PI0/filter.py
  nnpdf_data/nnpdf_data/commondata/STAR-2006_SHP_200GEV_PI0/kinematics.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2006_SHP_200GEV_PI0/metadata.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2006_SHP_200GEV_PI0/rawdata/HEPData-ins1253360-v1-Figure_7_Data.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2006_SHP_200GEV_PI0/uncertainties.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/data_highrap.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/data_lowrap.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/filter.py
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/kinematics_highrap.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/kinematics_lowrap.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/metadata.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/rawdata/HEPData-ins1674826-v1-Table_1.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/rawdata/HEPData-ins1674826-v1-Table_2.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/uncertainties_highrap.yaml
  nnpdf_data/nnpdf_data/commondata/STAR-2013_SHP_510GEV_PI0/uncertainties_lowrap.yaml
  validphys2/src/validphys/commondataparser.py
  validphys2/src/validphys/filters.py
  validphys2/src/validphys/process_options.py
Labels: data toolchain, Polarised

#2160 Minor fix evolven3fit with loaded eko
  n3fit/src/n3fit/scripts/evolven3fit.py
Labels: bug
