Repository NNPDF/nnpdf, pull requests merged in 2024-05, with the labels that each got.

#2028 Provide an unique truth for all theory cards
  n3fit/src/evolven3fit/eko_utils.py
  n3fit/src/n3fit/scripts/evolven3fit.py
  n3fit/src/n3fit/tests/conftest.py
  n3fit/src/n3fit/tests/test_evolven3fit.py
  nnpdf_data/nnpdf_data/theory.py
  nnpdf_data/nnpdf_data/theory_cards/41000000.yaml
  nnpdf_data/nnpdf_data/theorydbutils.py
  nnpdf_data/nnpdf_data/utils.py
  validphys2/src/validphys/photon/alpha.py
  validphys2/src/validphys/photon/compute.py
  validphys2/src/validphys/tests/photon/test_alpha.py
  validphys2/src/validphys/tests/photon/test_compute.py
  validphys2/src/validphys/tests/test_theorydbutils.py
Labels: run-fit-bot

#1895 ZPT 13 TeV dataset
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0J_13TEV_PT/data.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0J_13TEV_PT/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0J_13TEV_PT/filter_utils.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0J_13TEV_PT/kinematics.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0J_13TEV_PT/metadata.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0J_13TEV_PT/rawdata/HEPData-ins1768911-v3-Table_5.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0J_13TEV_PT/rawdata/HEPData-ins1768911-v3-Table_7.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0J_13TEV_PT/rawdata/HEPData-ins1768911-v3-Tabulated_Figure_6.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0J_13TEV_PT/uncertainties.yaml
  validphys2/src/validphys/cuts/filters.yaml
  validphys2/src/validphys/process_options.py
Labels: data toolchain

#2070 fix table chi2 grouped by
  validphys2/src/validphys/results.py
Labels: bug

#2068 update the closure test docs
  doc/sphinx/source/tutorials/closuretest.md
  n3fit/runcards/examples/Basic_runcard_closure_test.yml
  validphys2/src/validphys/closuretest/runcards/NNPDF40_closure_test.yml
  validphys2/src/validphys/closuretest/runcards/out_of_sample_NNPDF40_closure_test.yml
Labels: documentation

#2078 correct error message spelling
  validphys2/src/validphys/app.py
Labels: bug

#2077 removed duplicated DY_NC_PT process
  validphys2/src/validphys/process_options.py
Labels: bug

#2084 nnpdf31_process of positivity and integrability sets
  nnpdf_data/nnpdf_data/new_commondata/NNPDF_INTEG_3GEV/metadata.yaml
  nnpdf_data/nnpdf_data/new_commondata/NNPDF_POS_2P24GEV/metadata.yaml
Labels: bug

#2076 Hashable Rules
  conda-recipe/meta.yaml
  pyproject.toml
  validphys2/src/validphys/config.py
  validphys2/src/validphys/filters.py
  validphys2/src/validphys/loader.py
  validphys2/src/validphys/tests/test_filter_rules.py
  validphys2/src/validphys/utils.py
Labels: enhancement, Refactoring

#2065 Add restricted space hyperopt runcard
  n3fit/runcards/hyperopt_studies/restricted_search_space_renew_hyperopt.yml
Labels: escience
