Repository NNPDF/nnpdf, pull requests merged in 2024-04, with the labels that each got.

#2016 Add unique log files for each mongo worker
  n3fit/src/n3fit/hyper_optimization/mongofiletrials.py
Labels: escience

#2036 fix std_error function in MCStats class
  validphys2/src/validphys/core.py
  validphys2/src/validphys/tests/regressions/test_thprediction_results.csv
Labels: bug, run-fit-bot

#2031 Update to new commondata names - n3fit
  .github/workflows/fitbot.yml
  doc/sphinx/source/releases.rst
  doc/sphinx/source/tutorials/reproduce.rst
  n3fit/runcards/examples/Basic_feature_scaling.yml
  n3fit/runcards/examples/Basic_hyperopt.yml
  n3fit/runcards/examples/Basic_runcard.yml
  n3fit/runcards/examples/Basic_runcard_parallel.yml
  n3fit/runcards/examples/Basic_runcard_qed.yml
  n3fit/runcards/examples/DIS_diagonal_l2reg_example.yml
  n3fit/runcards/examples/Fit_with_theory_covmat.yml
  n3fit/runcards/examples/developing.yml
  n3fit/runcards/examples/nnpdf40-like.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_hyperopt.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_lo_as_01180.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_lo_pch_as_01180.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nlo_as_01170.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nlo_as_01180.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nlo_as_01190.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nlo_pch_as_01180.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01160.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01170.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01175.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01180_1000.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01180_hessian.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01185.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01190.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_as_01200.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_hessian_pdfas.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_pch_as_01180.yml
  n3fit/runcards/reproduce_nnpdf40/NNPDF40_nnlo_pdfas.yml
  n3fit/runcards/reproduce_nnpdf40/nnpdf40_env.yml
  n3fit/src/n3fit/hyper_optimization/rewards.py
  n3fit/src/n3fit/tests/regressions/filter.yml
  n3fit/src/n3fit/tests/regressions/hyper-quickcard.yml
  n3fit/src/n3fit/tests/regressions/noval-quickcard.yml
  n3fit/src/n3fit/tests/regressions/pc-quickcard.yml
  n3fit/src/n3fit/tests/regressions/quickcard-parallel.yml
  n3fit/src/n3fit/tests/regressions/quickcard-sequential.yml
  n3fit/src/n3fit/tests/regressions/quickcard.yml
  n3fit/src/n3fit/tests/regressions/quickcard_qed.yml
  n3fit/src/n3fit/tests/test_evolven3fit.py
  n3fit/src/n3fit/vpinterface.py
  validphys2/src/validphys/tests/test_commondata_columns.py
  validphys2/src/validphys/tests/test_commondataparser.py
Labels: run-fit-bot

#2045 Fixing bug in cholesky decompositions of ATLAS_2JET_7TEV_R06 in a closure_test
  validphys2/src/validphys/coredata.py
  validphys2/src/validphys/tests/test_commondataparser.py
Labels: bug

#2039 Polish EIC data files
  nnpdf_data/nnpdf_data/filter_utils/eic_utils.py
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_105GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_105GEV_EP/rawdata/ATHENA_ALL_EP.xlsx
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_105GEV_EP/rawdata/ATHENA_NC_105GEV_EP.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_140GEV_EP/athena_140gev_ep
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_140GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_140GEV_EP/rawdata/ATHENA_ALL_EP.xlsx
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_29GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_29GEV_EP/rawdata/ATHENA_ALL_EP.xlsx
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_29GEV_EP/rawdata/ATHENA_NC_29GEV_EP.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_45GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_45GEV_EP/rawdata/ATHENA_ALL_EP.xlsx
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_45GEV_EP/rawdata/ATHENA_NC_45GEV_EP.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_63GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_63GEV_EP/rawdata/ATHENA_ALL_EP.xlsx
  nnpdf_data/nnpdf_data/new_commondata/ATHENA_NC_63GEV_EP/rawdata/ATHENA_NC_63GEV_EP.yaml
  nnpdf_data/nnpdf_data/new_commondata/EIC_NC_211GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/EIC_NC_211GEV_EP/rawdata/EIC_18_275_A1c_100fb-1.txt
  nnpdf_data/nnpdf_data/new_commondata/EIC_NC_211GEV_EP/rawdata/EIC_NC_211GEV_EP.yaml
  nnpdf_data/nnpdf_data/new_commondata/EIC_NC_43GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/EIC_NC_43GEV_EP/rawdata/EIC_5_41_A1c_100fb-1.txt
  nnpdf_data/nnpdf_data/new_commondata/EIC_NC_43GEV_EP/rawdata/EIC_NC_43GEV_EP.yaml
  nnpdf_data/nnpdf_data/new_commondata/EIC_NC_67GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/EIC_NC_67GEV_EP/rawdata/EIC_5_100_A1c_100fb-1.txt
  nnpdf_data/nnpdf_data/new_commondata/EIC_NC_67GEV_EP/rawdata/EIC_NC_67GEV_EP.yaml
  nnpdf_data/nnpdf_data/new_commondata/EIcC_NC_15GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/EIcC_NC_15GEV_EP/rawdata/EIcC_3_20_A1c_100fb-1.txt
  nnpdf_data/nnpdf_data/new_commondata/EIcC_NC_15GEV_EP/rawdata/EIcC_NC_15GEV_EP.yaml
  nnpdf_data/nnpdf_data/new_commondata/EIcC_NC_22GEV_EP/filter.py
  nnpdf_data/nnpdf_data/new_commondata/EIcC_NC_22GEV_EP/rawdata/EIcC_5_25_A1c_100fb-1.txt
  nnpdf_data/nnpdf_data/new_commondata/EIcC_NC_22GEV_EP/rawdata/EIcC_NC_22GEV_EP.yaml
  nnpdf_data/pyproject.toml
Labels: data toolchain, Polarised, polish filter files

#2057 Improve sumrules module a bit by splitting operations
  validphys2/src/validphys/dataplots.py
  validphys2/src/validphys/sumrules.py
Labels: run-fit-bot

#2066 add validphys.commondata to vp-setupfits providers list
  n3fit/src/n3fit/scripts/vp_setupfit.py
Labels: bug
