Repository NNPDF/nnpdf, pull requests merged in 2024-06, with the labels that each got.

#2014 Ignore 10% worst replicas in hyper loss
  doc/sphinx/source/n3fit/hyperopt.rst
  doc/sphinx/source/n3fit/runcard_detailed.rst
  n3fit/runcards/hyperopt_studies/renew_hyperopt.yml
  n3fit/runcards/hyperopt_studies/restricted_search_space_renew_hyperopt.yml
  n3fit/src/n3fit/backends/keras_backend/multi_dense.py
  n3fit/src/n3fit/hyper_optimization/rewards.py
  n3fit/src/n3fit/model_trainer.py
  n3fit/src/n3fit/tests/regressions/hyper-quickcard.yml
Labels: escience

#2103 fix bug in _hqp_yq_xq2map process
  validphys2/src/validphys/process_options.py
  validphys2/src/validphys/tests/test_datafiles.py
Labels: bug

#2071 ATLAS lepton rapidity 8 TeV data
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0_8TEV_ZMASS/data.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0_8TEV_ZMASS/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0_8TEV_ZMASS/filter_utils.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0_8TEV_ZMASS/kinematics.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0_8TEV_ZMASS/metadata.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0_8TEV_ZMASS/rawdata/HEPData-ins2698794-v1-Table_9.yaml
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0_8TEV_ZMASS/rawdata/zy.txt
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_Z0_8TEV_ZMASS/uncertainties.yaml
Labels: data toolchain

#2100 Fix new commondata filters
  nnpdf_data/nnpdf_data/filter_utils/utils.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_1JET_13TEV_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_2JET_13TEV_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_TTBAR_13TEV_HADR_DIF/artunc.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_TTBAR_13TEV_HADR_DIF/utils.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_TTBAR_13TEV_LJ_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_TTBAR_8TEV_2L_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_TTBAR_8TEV_LJ_DIF/artunc.py
  nnpdf_data/nnpdf_data/new_commondata/ATLAS_TTBAR_8TEV_LJ_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/CMS_TTBAR_13TEV_2L_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/CMS_TTBAR_13TEV_LJ_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/CMS_TTBAR_8TEV_2L_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/CMS_TTBAR_8TEV_LJ_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/CMS_WPWM_7TEV_ELECTRON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/CMS_WPWM_7TEV_MUON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/CMS_WPWM_8TEV_MUON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/CMS_Z0_7TEV_DIMUON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/H1_1JET_319GEV_290PB-1_DIF/artUnc.py
  nnpdf_data/nnpdf_data/new_commondata/H1_1JET_319GEV_290PB-1_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/H1_1JET_319GEV_351PB-1_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/H1_1JET_319GEV_351PB-1_DIF/manual_impl.py
  nnpdf_data/nnpdf_data/new_commondata/H1_2JET_319GEV_290PB-1_DIF/artUnc.py
  nnpdf_data/nnpdf_data/new_commondata/H1_2JET_319GEV_290PB-1_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/H1_2JET_319GEV_351PB-1_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/H1_2JET_319GEV_351PB-1_DIF/manual_impl.py
  nnpdf_data/nnpdf_data/new_commondata/LHCB_DY_7TEV_MUON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/LHCB_DY_8TEV_MUON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/LHCB_WPWM_7TEV_MUON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/LHCB_WPWM_8TEV_MUON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/LHCB_Z0_13TEV/filter.py
  nnpdf_data/nnpdf_data/new_commondata/LHCB_Z0_7TEV_DIELECTRON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/LHCB_Z0_7TEV_MUON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/LHCB_Z0_8TEV_DIELECTRON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/LHCB_Z0_8TEV_MUON/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ZEUS_1JET_300GEV_38P6PB-1_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ZEUS_1JET_319GEV_82PB-1_DIF/filter.py
  nnpdf_data/nnpdf_data/new_commondata/ZEUS_2JET_319GEV_374PB-1_DIF/filter.py
Labels: data toolchain, polish filter files

#2114 make sure tempfile is alive when it's used
  validphys2/src/validphys/loader.py
Labels: bug

#2119 replace scipy.integrate.simps which has been removed in favor of simpson
  validphys2/src/validphys/arclength.py
Labels: bug

#2116 replace POS_F2 process with more inclusive POS_DIS
  nnpdf_data/nnpdf_data/new_commondata/NNPDF_POS_2P24GEV/kinematics_FLL-19PTS.yaml
  nnpdf_data/nnpdf_data/new_commondata/NNPDF_POS_2P24GEV/kinematics_FLL.yaml
  nnpdf_data/nnpdf_data/new_commondata/NNPDF_POS_2P24GEV/metadata.yaml
  validphys2/src/validphys/process_options.py
Labels: bug

#2079 Polarized STAR and PHENIX A_L W
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/data_wm.yaml
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/data_wp.yaml
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/filter.py
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/kinematics_wm.yaml
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/kinematics_wp.yaml
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/metadata.yaml
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/rawdata/Figure5,A_LforW^+rightarrowe^+,combineddatasamples.csv
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/rawdata/Figure5,A_LforW^-rightarrowe^-,combineddatasamples.csv
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/uncertainties_wm.yaml
  nnpdf_data/nnpdf_data/new_commondata/STAR_WMWP_510GEV/uncertainties_wp.yaml
  nnpdf_data/nnpdf_data/new_commondata/STAR_WM_510GEV/filter.py
  nnpdf_data/nnpdf_data/new_commondata/STAR_WM_510GEV/metadata.yaml
  nnpdf_data/nnpdf_data/new_commondata/STAR_WP_510GEV/filter.py
  nnpdf_data/nnpdf_data/new_commondata/STAR_WP_510GEV/metadata.yaml
Labels: data toolchain, Polarised
